### ISSUE TITLE
Max 33% width for products on desktop and tablet in collection view

### ISSUE THREAD

**Issue by prebenpreben** [hyttefeber/dawn#38]
**Describe the enhancement you'd like**
Currently, a user can filter down to 1 or 2 products on tablet and mobile, and it will be 50% or 100% width. This causes pixelated images in most cases, as well as other components like buttons and so on are not aesthetically pleasing.

Our simple fix for that is to cap it at 33% width, for desktop and tablet to make the collection view feel more consistent and familiar and avoid big layout shifts.

Should be a quick fix, but I wasn't able to code it myself without breaking stuff.

**Comment by olafghanizadeh** [comment]
Like this
<img width="2560" alt="Screenshot 2022-03-10 at 09 02 51" src="https://user-images.githubusercontent.com/25170177/157627746-a082de17-87e4-432f-a180-4ab079aed075.png">
?

**Comment by prebenpreben** [comment]
Close! It should only apply when there are less than 4 products visible in the collection. Meaning the 50% and 100% width when 1 or 2 should be overwritten with 33%. So a product can only ever take up a maximum of 33% in the width. 
If you try filtering down to one or two products in a collection on desktop or mobile, you'll see why we want this.
